// Generated by scripts/sync-changelog.mjs — do not edit by hand.
export const releases: Record<string, { version: string; date: string }> = {
  'expo-devtools': { version: '2.4.1', date: '29 August 2026' },
};
